### ISSUE TITLE
Serpent.AI Hello World Example // self.input_controller.tap_key("right")  => AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by Ben910128** [SerpentAI/SerpentAI#104]
* **Operating System:** macOS
* **Serpent Version:** (e.g. 0.1.6b1)
* **Game:** App Store : 2048 Game
* **Backend:** CPU

### Expected result
according to Serpent.AI Hello World Example, when I add `self.input_controller.tap_key("right")` in the last, it always through out like below,

### Encountered result
```python
{'width': 480, 'height': 560, 'x_offset': 0, 'y_offset': 23}
/Users/ben/.virtualenvs/serpent/lib/python3.6/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/Users/ben/.virtualenvs/serpent/lib/python3.6/site-packages/skimage/util/dtype.py:122: UserWarning: Possible precision loss when converting from float64 to uint8
  .format(dtypeobj_in, dtypeobj_out))
hello world!
Traceback (most recent call last):
  File "/Users/ben/.virtualenvs/serpent/bin/serpent", line 11, in <module>
    load_entry_point('SerpentAI==0.1.12b1', 'console_scripts', 'serpent')()
  File "/Users/ben/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 48, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/Users/ben/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 238, in play
    game.play(game_agent_class_name=game_agent_name, frame_handler=frame_handler)
  File "/Users/ben/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/game.py", line 186, in play
    raise e
  File "/Users/ben/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/game.py", line 177, in play
    game_agent.on_game_frame(game_frame, frame_handler=frame_handler, **kwargs)
  File "/Users/ben/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/game_agent.py", line 89, in on_game_frame
    frame_handler(game_frame, **kwargs)
  File "/Users/ben/01_ProjectsForFun/SerpentAI/plugins/SerpentA2048GameGameAgentPlugin/files/serpent_A2048Game_game_agent.py", line 26, in handle_play
    self.input_controller.press_key('right')
  File "/Users/ben/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/input_controller.py", line 277, in press_key
    self.backend.press_key(key, **kwargs)
  File "/Users/ben/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/input_controllers/pyautogui_input_controller.py", line 186, in press_key
    pyautogui.keyDown(keyboard_key_mapping[key.name])
AttributeError: 'str' object has no attribute 'name'
```
### Steps to reproduce
fellow the example completely, when i comment `self.input_controller.tap_key("right")` everything runs normal, error occurred after uncomment it.

**Comment by nbrochu** [comment]
Did you follow the Chinese wiki? Perhaps a command is out of date in there. 

Check the code here for the right command [https://github.com/SerpentAI/SerpentAI/wiki/The-Serpent.AI-Hello-World](https://github.com/SerpentAI/SerpentAI/wiki/The-Serpent.AI-Hello-World)

**Comment by Ben910128** [comment]
Yes. It works well now , thank you. I will update the Chinese wiki.
