### ISSUE TITLE
Unknown Issue when I try to do the Hello World task

### ISSUE THREAD

**Issue by JJack27** [SerpentAI/SerpentAI#105]
* **Operating System:** Linux
* **Serpent Version:** (e.g. 0.1.6b1)
* **MiniMetro:** (link to steam page or game)
* **CPU:** GPU/CPU

### Expected result
Hello World
### Encountered result
Traceback (most recent call last):
  File "/home/jack27/.pyenv/versions/serpent/bin/serpent", line 11, in <module>
    load_entry_point('SerpentAI==0.1.12b1', 'console_scripts', 'serpent')()
  File "/home/jack27/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 48, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/home/jack27/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 230, in play
    game.launch(dry_run=True)
  File "/home/jack27/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 124, in launch
    self.after_launch()
  File "/home/jack27/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 134, in after_launch
    self.window_id = self.window_controller.locate_window(self.window_name)
  File "/home/jack27/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/window_controller.py", line 14, in locate_window
    return self.adapter.locate_window(name)
  File "/home/jack27/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/window_controllers/linux_window_controller.py", line 15, in locate_window
    return subprocess.check_output(shlex.split(f"xdotool search --onlyvisible --name \"^{name}$\"")).decode("utf-8").strip()
  File "/home/jack27/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/jack27/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['xdotool', 'search', '--onlyvisible', '--name', '^MiniMetro Plugin$']' returned non-zero exit status 1.

### Steps to reproduce

1. 
2. 
3.

**Comment by nbrochu** [comment]
Wrong window name in your game plugin. It needs to be the name in the title bar of the game on Linux.

You can run `serpent window_name` to get the exact name you need to put in there.

**Comment by JJack27** [comment]
Thank you for your helping. But the program still not working, it shows:

{'width': 1280, 'height': 720, 'x_offset': 0, 'y_offset': 61}
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  7
  Current serial number in output stream:  7

**Comment by nbrochu** [comment]
Can I see what's in your Game Plugin?

**Comment by JJack27** [comment]
`from serpent.game_agent import GameAgent


class SerpentMiniMetroGameAgent(GameAgent):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.frame_handlers["PLAY"] = self.handle_play

        self.frame_handler_setups["PLAY"] = self.setup_play

        self.analytics_client = None

    def setup_play(self):
        pass

    def handle_play(self, game_frame):
        print("Hello World")`

And 
`import offshoot


class SerpentMiniMetroGameAgentPlugin(offshoot.Plugin):
    name = "SerpentMiniMetroGameAgentPlugin"
    version = "0.1.0"

    plugins = []

    libraries = []

    files = [
        {"path": "serpent_MiniMetro_game_agent.py", "pluggable": "GameAgent"}
    ]

    config = {
        "frame_handler": "PLAY"
    }

    @classmethod
    def on_install(cls):
        print("\n\n%s was installed successfully!" % cls.__name__)

    @classmethod
    def on_uninstall(cls):
        print("\n\n%s was uninstalled successfully!" % cls.__name__)


if __name__ == "__main__":
    offshoot.executable_hook(SerpentMiniMetroGameAgentPlugin)`

**Comment by nbrochu** [comment]
I meant the other one; The game plugin, not the game agent >.>
