### ISSUE TITLE
Weird string of errors in log when doing the hello world demo with Super hexagon

### ISSUE THREAD

**Issue by thesmarthomeninja** [SerpentAI/SerpentAI#120]
My environment
* **Operating System:** Linux/Windows/macOS ubuntu 16.04

* **Serpent Version:** (e.g. 0.1.6b1)  - the latest version as I just downloaded the package again and created a new virtual env before reproducing this error

* **Game:** (link to steam page or game) super hexagon

* **Backend:** GPU/CPU - using intel QM2860 quad core and Nvidia 2000M -laptop video card (I'm using the CPU for running tensorflow per the warning on the GTX 600 minimum needed) 

I type in serpent launch superhexagon and get this log below in encountered result.  I basically got an offshoot.yml error, so checked my venv and realized it was that, then I got another error on xdotool not being recognized so I sudo apt installed xdo tool to get rid of that.  When I finally was able to launch the game it went full screen and gave me this error log below.  Any ideas on what caused this or something I might be missing?  Thanks!!!

### Expected result
after launch of game- it doesn't reposition in the top left after doing the "Hello World" demo section

### Encountered result
The game starts in full screen mode after it launches from steam successfully
(serpent_test) kalendaniel@NewUbuntu:~/serpent_test/serpent$ serpent launch superhexagon
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Traceback (most recent call last):
  File "/home/kalendaniel/serpent_test/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/home/kalendaniel/serpent_test/lib/python3.6/site-packages/serpent/serpent.py", line 48, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/home/kalendaniel/serpent_test/lib/python3.6/site-packages/serpent/serpent.py", line 217, in launch
    game().launch()
  File "/home/kalendaniel/serpent_test/lib/python3.6/site-packages/serpent/game.py", line 124, in launch
    self.after_launch()
  File "/home/kalendaniel/serpent_test/lib/python3.6/site-packages/serpent/game.py", line 134, in after_launch
    self.window_id = self.window_controller.locate_window(self.window_name)
  File "/home/kalendaniel/serpent_test/lib/python3.6/site-packages/serpent/window_controller.py", line 14, in locate_window
    return self.adapter.locate_window(name)
  File "/home/kalendaniel/serpent_test/lib/python3.6/site-packages/serpent/window_controllers/linux_window_controller.py", line 15, in locate_window
    return subprocess.check_output(shlex.split(f"xdotool search --onlyvisible --name \"^{name}$\"")).decode("utf-8").strip()
  File "/home/kalendaniel/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/kalendaniel/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['xdotool', 'search', '--onlyvisible', '--name', '^superhexagon$']' returned non-zero exit status 1.

### Steps to reproduce

1. Installed all packages and requirements
2. Created virtual environment and fixed that issue I had with offshoot.yml
3. Installed game plugin and modified the game plugin .py file with the name of the game and the app ID and then launched the game from the terminal.  Not using an IDE, did this all from CLI running my python version 3.6.2 with ubuntu through command line pretty much.  Hope this helps identifying what I'm doing wrong.

**Comment by thesmarthomeninja** [comment]
Also, I changed the options in the game settings inside of the game to window mode, to see if that made a difference, and I did update the game agent .py file to include hello world.  But I'm just not sure if I did these last couple of steps right since it just gives that long log above and goes right back to the prompt right after the game starts. figured maybe im missing a package or something, not entirely sure as I'm fairly newer with a lot of these packages and steam sadly...

**Comment by thesmarthomeninja** [comment]
nvm- sorry if I wasted anyone's time.  I am doing it in between breaks at work and did a google query and found this.

**Comment by thesmarthomeninja** [comment]
https://github.com/SerpentAI/SerpentAI/issues/105

**Comment by thesmarthomeninja** [comment]
duplicated issue that already has been solved #105
