### ISSUE TITLE
ValueError: cannot reshape array of size 0 into shape (0,newaxis)

### ISSUE THREAD

**Issue by cacao1987** [SerpentAI/SerpentAI#127]
* **Operating System:** Windows 10
* **Serpent Version:latest
* **Game:**  YouMustBuildABoat
* **Backend:** CPU

### Encountered result

serpent play YouMustBuildABoat SerpentYouMustBuildABoatGameAgent
{'width': 683, 'height': 512, 'x_offset': 2, 'y_offset': 25}
Using TensorFlow backend.
plugin_path: plugins
Found 1310 images belonging to 11 classes.
Found 139 images belonging to 11 classes.
2017-12-27 02:27:29.893064: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\uboat\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\uboat\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\UBoat\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\envs\uboat\lib\site-packages\serpent\serpent.py", line 48, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\programdata\anaconda3\envs\uboat\lib\site-packages\serpent\serpent.py", line 238, in play
    game.play(game_agent_class_name=game_agent_name, frame_handler=frame_handler)
  File "c:\programdata\anaconda3\envs\uboat\lib\site-packages\serpent\game.py", line 186, in play
    raise e
  File "c:\programdata\anaconda3\envs\uboat\lib\site-packages\serpent\game.py", line 177, in play
    game_agent.on_game_frame(game_frame, frame_handler=frame_handler, **kwargs)
  File "c:\programdata\anaconda3\envs\uboat\lib\site-packages\serpent\game_agent.py", line 89, in on_game_frame
    frame_handler(game_frame, **kwargs)
  File "C:\Windows\System32\SerpentAI\plugins\SerpentYouMustBuildABoatGameAgentPlugin\files\serpent_YouMustBuildABoat_game_agent.py", line 174, in handle_play
    self.handle_play_context_level(game_frame)
  File "C:\Windows\System32\SerpentAI\plugins\SerpentYouMustBuildABoatGameAgentPlugin\files\serpent_YouMustBuildABoat_game_agent.py", line 261, in handle_play_context_level
    self.game_board = self.game.api.parse_game_board(game_frame.frame, self.game, self.sprite_identifier)
  File "C:\Windows\System32\SerpentAI\plugins\SerpentYouMustBuildABoatGamePlugin\files\api\api.py", line 70, in parse_game_board
    cell_sprite = Sprite(screen_region, image_data=cell[:, :, :, np.newaxis])
  File "c:\programdata\anaconda3\envs\uboat\lib\site-packages\serpent\sprite.py", line 23, in __init__
    self.signature_colors = signature_colors or self._generate_signature_colors()
  File "c:\programdata\anaconda3\envs\uboat\lib\site-packages\serpent\sprite.py", line 69, in _generate_signature_colors
    values, counts = np.unique(self.image_data[..., i].reshape(width * height, pixels), axis=0, return_counts=True)
  File "c:\programdata\anaconda3\envs\uboat\lib\site-packages\numpy\lib\arraysetops.py", line 217, in unique
    ar = ar.reshape(orig_shape[0], -1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)

**Comment by nbrochu** [comment]
I'll try to get back to you soon on this. A little busy with the Holidays. It seems your frame grabber is not capturing anything and it's passing an empty array in as a sprite. Try to use `serpent capture frame YouMustBuildABoat 1` first and make sure some frames are saved to disk when you focus out of the games after a while.

**Comment by cacao1987** [comment]
thanks for you reply, @nbrochu ,I have used command `serpent  frame YouMustBuildABoat 1`, the  result seems to be ok，but the problem above still exists.

![capture](https://user-images.githubusercontent.com/10770048/34403172-a0dc6f02-ebe1-11e7-9474-15aa207f207d.jpg)

**Comment by nbrochu** [comment]
I'd need to see your current Game and Game Agent Plugins to help further. You can make a gist with their contents and share here.
