### ISSUE TITLE
The Plugin definition specifies an invalid pluggable

### ISSUE THREAD

**Issue by sherlockZ** [SerpentAI/SerpentAI#129]
* **Operating System:** macOS
* **Serpent Version:** (e.g. 0.1.6b1)
* **Game:** (link to steam page or game)
* **Backend:** CPU

What is the name of the game? (Titleized, No Spaces i.e. AwesomeGame):
FlappyBird
How is the game launched? (One of: 'steam', 'executable', 'web_browser'):
executable
/usr/local/Cellar/python3/HEAD-e5681b9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/offshoot/base.py:38: UserWarning: 'offshoot.yml' not found! Using default configuration.
  warnings.warn("'offshoot.yml' not found! Using default configuration.")
/usr/local/Cellar/python3/HEAD-e5681b9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/offshoot/base.py:38: UserWarning: 'offshoot.yml' not found! Using default configuration.
  warnings.warn("'offshoot.yml' not found! Using default configuration.")
OFFSHOOT: Attempting to install SerpentFlappyBirdGamePlugin...
/usr/local/Cellar/python3/HEAD-e5681b9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/offshoot/base.py:38: UserWarning: 'offshoot.yml' not found! Using default configuration.
  warnings.warn("'offshoot.yml' not found! Using default configuration.")

OFFSHOOT PLUGIN INSTALL: Verifying that plugin dependencies are installed...

OFFSHOOT PLUGIN INSTALL: Installing files...

There was a problem during installation... Reverting!
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/HEAD-e5681b9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/HEAD-e5681b9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sherlock/git/SerpentAI/plugins/SerpentFlappyBirdGamePlugin/plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpentFlappyBirdGamePlugin)
  File "/usr/local/Cellar/python3/HEAD-e5681b9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/offshoot/base.py", line 178, in executable_hook
    plugin_class.install()
  File "/usr/local/Cellar/python3/HEAD-e5681b9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/offshoot/plugin.py", line 35, in install
    cls.install_files()
  File "/usr/local/Cellar/python3/HEAD-e5681b9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/offshoot/plugin.py", line 118, in install_files
    raise e
  File "/usr/local/Cellar/python3/HEAD-e5681b9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/offshoot/plugin.py", line 91, in install_files
    is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])
  File "/usr/local/Cellar/python3/HEAD-e5681b9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/offshoot/plugin.py", line 235, in _validate_file_for_pluggable
    raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))
offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins/SerpentFlappyBirdGamePlugin/files/serpent_FlappyBird_game.py => Game

**Comment by Jailman** [comment]
The serpenai developers' holidays are sooooo long!

**Comment by anoadragon453** [comment]
Getting the same thing coming in from the [Hello World wiki page](https://github.com/SerpentAI/SerpentAI/wiki/The-Serpent.AI-Hello-World):

```
What is the name of the game? (Titleized, No Spaces i.e. AwesomeGame): 
SuperHexagon
How is the game launched? (One of: 'steam', 'executable', 'web_browser'): 
steam
OFFSHOOT: Attempting to install SerpentSuperHexagonGamePlugin...

OFFSHOOT PLUGIN INSTALL: Verifying that plugin dependencies are installed...


OFFSHOOT PLUGIN INSTALL: Installing files...

/home/user/.pyenv/versions/serpent/lib/python3.6/site-packages/offshoot/base.py:63: UserWarning: 'serpent.game' does not appear to be a valid module. Skipping!
  warnings.warn("'%s' does not appear to be a valid module. Skipping!" % m)
/home/user/.pyenv/versions/serpent/lib/python3.6/site-packages/offshoot/base.py:63: UserWarning: 'serpent.game_agent' does not appear to be a valid module. Skipping!
  warnings.warn("'%s' does not appear to be a valid module. Skipping!" % m)

There was a problem during installation... Reverting!
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.6.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/.pyenv/versions/3.6.2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/Documents/SerpentAI/SerpentAI/plugins/SerpentSuperHexagonGamePlugin/plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpentSuperHexagonGamePlugin)
  File "/home/user/.pyenv/versions/serpent/lib/python3.6/site-packages/offshoot/base.py", line 178, in executable_hook
    plugin_class.install()
  File "/home/user/.pyenv/versions/serpent/lib/python3.6/site-packages/offshoot/plugin.py", line 35, in install
    cls.install_files()
  File "/home/user/.pyenv/versions/serpent/lib/python3.6/site-packages/offshoot/plugin.py", line 118, in install_files
    raise e
  File "/home/user/.pyenv/versions/serpent/lib/python3.6/site-packages/offshoot/plugin.py", line 91, in install_files
    is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])
  File "/home/user/.pyenv/versions/serpent/lib/python3.6/site-packages/offshoot/plugin.py", line 235, in _validate_file_for_pluggable
    raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))
offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins/SerpentSuperHexagonGamePlugin/files/serpent_SuperHexagon_game.py => Game
(serpent) user@localhost:~/Documents/SerpentAI/SerpentAI$ 
```

**Comment by nbrochu** [comment]
The most common reason for this happening is not running your commands in the folder where you ran `serpent setup`. The setup prepares that specific folder to generate plugins. If you are positive you are in the same folder, make sure you are in the correct virtualenv where serpent was installed.

I'm thinking it's the former because you can see it complains about a missing offshoot.yml and that's something that gets created by `serpent setup`

**Comment by JulianNorton** [comment]
This is happening to me too with a fresh install, following the documentation exactly.

**Comment by stsievert** [comment]
At the top of the wiki, there's

> *Note: Before proceeding with this guide, make sure you have followed the installation guide for your OS, including running 'serpent setup'*

This wasn't clear to me. Maybe highlight "include running 'serpent setup'" in bold or something?

**Comment by f1recracker** [comment]
I was facing this exact issue after following the documentation as well. Turns out I needed to run the command from the SerpentAI root directory.

**Comment by JulianNorton** [comment]
@f1recracker `(C:\ProgramData\Anaconda3) C:\Windows\System32\SerpentAI>` is my path, still getting the pluggable error.

**Comment by popey456963** [comment]
Also getting same issues, ran `serpent setup` in every folder I could think of running it :)

**Comment by Exaltia** [comment]
I had the same error, files created. i tried to follow the nest step of the tutorial, to no success, SerpentAi telling Exception: Game 'Osmos' wasn't found. Make sure the plugin is installed.

Unless the python code needs things that are not created because the scripts fails, i assumed that it should find his plugins anyways.
I had made that little test (OS : Windows 10 1709(16299.248, Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
 os.path.isdir('plugins\SerpentOsmosGamePlugin\files')
False
>>> os.path.isdir('plugins\SerpentOsmosGamePlugin\Files')
True
I'm far from being the best expert on python, but could it be the problem?

**Comment by ftbabi** [comment]
This happened to me, too. 
I tried to run the command in the folder which was created by running "mkproject projectname", and it works! Thanks to what the author said!
