### ISSUE TITLE
ddqn.py, function load_model_weights

### ISSUE THREAD

**Issue by arixlin** [SerpentAI/SerpentAI#131]
* **Operating System:Windows7
* **Serpent Version:** (e.g. 0.1.6b1)
* **Game:** (link to steam page or game)
* **Backend:** GPU
when  I restore the model:
### Expected result
Traceback (most recent call last):
  File "d:\programdata\anaconda3\envs\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\envs\python36\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\serpent\serpent.py", line 48, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\serpent\serpent.py", line 238, in play
    game.play(game_agent_class_name=game_agent_name, frame_handler=frame_handler)
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\serpent\game.py", line 186, in play
    raise e
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\serpent\game.py", line 177, in play
    game_agent.on_game_frame(game_frame, frame_handler=frame_handler, **kwargs)
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\serpent\game_agent.py", line 85, in on_game_frame
    self._setup_frame_handler(frame_handler=frame_handler, **kwargs)
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\serpent\game_agent.py", line 209, in _setup_frame_handler
    self.frame_handler_setups[frame_handler](**kwargs)
  File "d:\github\SerpentAI\plugins\SerpenthornetGameAgentPlugin\files\serpent_hornet_game_agent.py", line 136, in setup_play
    raise e
  File "d:\github\SerpentAI\plugins\SerpenthornetGameAgentPlugin\files\serpent_hornet_game_agent.py", line 133, in setup_play
    self.dqn_movement.load_model_weights(file_path='model/binding_of_isacc_movement_dqn.h5', override_epsilon=True)
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\serpent\machine_learning\reinforcement_learning\ddqn.py", line 131, in load_model_weights
    self.model_online.compile(loss="logcosh", optimizer=Adam(lr=self.model_learning_rate, clipvalue=10))
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\keras\engine\training.py", line 740, in compile
    loss_function = losses.get(loss)
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\keras\losses.py", line 90, in get
    return deserialize(identifier)
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\keras\losses.py", line 82, in deserialize
    printable_module_name='loss function')
  File "d:\programdata\anaconda3\envs\python36\lib\site-packages\keras\utils\generic_utils.py", line 157, in deserialize_keras_object
    ':' + function_name)
ValueError: ('Unknown loss function', ':logcosh')

**Comment by nbrochu** [comment]
Can't say I know what's up from the top of my head. I'll take a look.

**Comment by arixlin** [comment]
@nbrochu when I update keras version to keras-2.1.2 is solved,  conda's version is 2.0.2  has  not func logcosh.
THX!

**Comment by nbrochu** [comment]
huh, interesting that Anaconda didn't have a good enough Keras version.
