### ISSUE TITLE
Redis.exceptions.InvalidResponse：Protocol error,got "H" as reply type byte

### ISSUE THREAD

**Issue by lwychj** [SerpentAI/SerpentAI#147]
Operating System: Windows10
Serpent.AI Version: lastest version
Game: Battlerite
Backend: GPU

### Expected result
Serpent should open a visual debugger
### Encountered result
 Traceback (most recent call last):
   File "d:\anaconda\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "d:\anaconda\envs\serpent\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "D:\Anaconda\envs\serpent\Scripts\serpent.exe\__main__.py", line 9, in <module>
   File "d:\anaconda\envs\serpent\lib\site-packages\serpent\serpent.py", line 48, in execute
     command_function_mapping[command](*sys.argv[2:])
   File "d:\anaconda\envs\serpent\lib\site-packages\serpent\serpent.py", line 281, in visual_debugger
     VisualDebuggerApp(buckets=buckets or None).run()
   File "d:\anaconda\envs\serpent\lib\site-packages\serpent\visual_debugger\visual_debugger_app.py", line 29, in __init__
     self.visual_debugger = VisualDebugger(buckets=buckets)
   File "d:\anaconda\envs\serpent\lib\site-packages\serpent\visual_debugger\visual_debugger.py", line 19, in __init__
     self.clear_image_data()
   File "d:\anaconda\envs\serpent\lib\site-packages\serpent\visual_debugger\visual_debugger.py", line 51, in clear_image_data
     visual_debugger_keys = self.redis_client.keys(f"{config['visual_debugger']['redis_key_prefix']}*")
   File "d:\anaconda\envs\serpent\lib\site-packages\redis\client.py", line 1032, in keys
     return self.execute_command('KEYS', pattern)
   File "d:\anaconda\envs\serpent\lib\site-packages\redis\client.py", line 668, in execute_command
     return self.parse_response(connection, command_name, **options)
   File "d:\anaconda\envs\serpent\lib\site-packages\redis\client.py", line 680, in parse_response
     response = connection.read_response()
   File "d:\anaconda\envs\serpent\lib\site-packages\redis\connection.py", line 624, in read_response
     response = self._parser.read_response()
   File "d:\anaconda\envs\serpent\lib\site-packages\redis\connection.py", line 408, in read_response
     response = self._reader.gets()
 redis.exceptions.InvalidResponse: Protocol error, got "H" as reply type byte
### Steps to reproduce

1. Generate a game plugin
2. serpent launch Battlerite
3. serpent visual_debugger

**Comment by nbrochu** [comment]
Acknowledged. I'll try to repro soon. Which redis are you using?

**Comment by lwychj** [comment]
I don't know,I downloaded it by pip

**Comment by sl1msh4dy** [comment]
https://github.com/MicrosoftArchive/redis/releases

**Comment by lwychj** [comment]
Thanks.I tried but it's still this problem
