### ISSUE TITLE
[Bug] [Windows] "No module named 'win32gui'" prevents 'serpent launch game'

### ISSUE THREAD

**Issue by shisatum** [SerpentAI/SerpentAI#149]
* **Operating System:** Windows 10
* **Serpent.AI Version:** SerpentAI-2018.1.0 offshoot-0.1.6
* **Game:** Any
* **Backend:** i5 and GTX 1060 3GB

### Expected result
`serpent launch game` executes successfully

### Encountered result
```
(serpent) C:\Users\Puter\SerpentAI>serpent launch game
Traceback (most recent call last):
  File "c:\users\puter\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\puter\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Puter\Anaconda3\envs\serpent\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\users\puter\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\users\puter\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 349, in launch
    game = initialize_game(game_name)
  File "c:\users\puter\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 580, in initialize_game
    game = game_class()
  File "c:\users\puter\anaconda3\envs\serpent\lib\site-packages\serpent\utilities.py", line 97, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\Puter\SerpentAI\plugins\Serpentsc_combatGamePlugin\files\serpent_sc_combat_game.py", line 14, in __init__
    super().__init__(**kwargs)
  File "c:\users\puter\anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 57, in __init__
    self.window_controller = WindowController()
  File "c:\users\puter\anaconda3\envs\serpent\lib\site-packages\serpent\window_controller.py", line 11, in __init__
    self.adapter = self._load_adapter()()
  File "c:\users\puter\anaconda3\envs\serpent\lib\site-packages\serpent\window_controller.py", line 42, in _load_adapter
    from serpent.window_controllers.win32_window_controller import Win32WindowController
  File "c:\users\puter\anaconda3\envs\serpent\lib\site-packages\serpent\window_controllers\win32_window_controller.py", line 3, in <module>
    import win32gui
ModuleNotFoundError: No module named 'win32gui'
```

### Steps to reproduce
Create a plugin on Windows via `serpent generate game` and try to launch it. ie: `serpent launch game`

### Additional details
```
(serpent) C:\Users\Puter\SerpentAI>pip install win32gui
Requirement already satisfied: win32gui in c:\users\puter\anaconda3\envs\serpent\lib\site-packages
Requirement already satisfied: win32core in c:\users\puter\anaconda3\envs\serpent\lib\site-packages (from win32gui)

(serpent) C:\Users\Puter\SerpentAI>pip3 install win32gui
Requirement already satisfied: win32gui in c:\users\puter\appdata\local\programs\python\python36\lib\site-packages
Requirement already satisfied: win32core in c:\users\puter\appdata\local\programs\python\python36\lib\site-packages (from win32gui)

(serpent) C:\Users\Puter\SerpentAI>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32gui'
>>>
```

**Comment by shisatum** [comment]
Closing as not a bug: The issue was a conflicting Python3 install. Removing it and reinstalling Anaconda and Serpent.AI resolved this error.

**Comment by woctezuma** [comment]
I still have this issue after removing SerpentAI and Anaconda, and then reinstalling both.
