### ISSUE TITLE
[Bug] Can't record on Windows 10

### ISSUE THREAD

**Issue by shisatum** [SerpentAI/SerpentAI#150]
* **Operating System:** Windows 10
* **Serpent.AI Version:** 2018.1.0
* **Game:** http://store.steampowered.com/app/732430/Superflight/
* **Backend:** GTX 1060 3GB / i5-6600

### Expected result
SerpentAI records data from me playing to an .h5 file.

### Encountered result
SerpentAI errors and .h5 file is not created.
```
(serpent) C:\Users\Puter\SerpentAI>serpent launch SuperFlight
{'width': 1920, 'height': 1080, 'x_offset': 0, 'y_offset': 0}

(serpent) C:\Users\Puter\SerpentAI>serpent record SuperFlight SerpentSuperFlightGameAgent
{'width': 0, 'height': 0, 'x_offset': -31920, 'y_offset': -32052}
c:\users\puter\anaconda3\lib\site-packages\skimage\transform\_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
Traceback (most recent call last):
  File "c:\users\puter\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\puter\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Puter\Anaconda3\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\serpent.py", line 312, in grab_frames
    frame_grabber.start()
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\frame_grabber.py", line 59, in start
    frame_pipeline = self.frame_transformation_pipeline.transform(frame)
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\frame_transformation_pipeline.py", line 32, in transform
    frame = pipeline_func(frame, *args)
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\frame_transformer.py", line 18, in resize
    return skimage.util.img_as_ubyte(skimage.transform.resize(frame, (int(height), int(width))))
  File "c:\users\puter\anaconda3\lib\site-packages\skimage\transform\_warps.py", line 135, in resize
    preserve_range=preserve_range)
  File "c:\users\puter\anaconda3\lib\site-packages\skimage\transform\_warps.py", line 819, in warp
    _clip_warp_output(image, warped, order, mode, cval, clip)
  File "c:\users\puter\anaconda3\lib\site-packages\skimage\transform\_warps.py", line 570, in _clip_warp_output
    min_val = input_image.min()
  File "c:\users\puter\anaconda3\lib\site-packages\numpy\core\_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

### Steps to reproduce
In the Anaconda Prompt running as Administrator:
```
conda create --name serpent python=3.6
mkdir C:\Users\Puter\SerpentAI
cd C:\Users\Puter\SerpentAI
activate serpent
pip install SerpentAI
serpent setup
serpent generate game
serpent generate game_agent
```
At this point, edit the game and game agent files as recommended per https://www.youtube.com/watch?v=hIFkdao0ELU
```
serpent launch SuperFlight
serpent record SuperFlight SerpentSuperFlightGameAgent
```

**Comment by shisatum** [comment]
Additionally, if I remove comment out `self.frame_transformation_pipeline_string = "RESIZE:200x200|FLOAT"` from `serpent_SuperFlight_game.py`, recording seems to occur, but errors upon recording the .h5 file:
```
Writing Recorded Input Data to 'datasets/input_recording.h5'... (1/538)
Traceback (most recent call last):
  File "c:\users\puter\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\puter\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Puter\Anaconda3\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\serpent.py", line 374, in record
    frame_spacing=int(frame_spacing)
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\game.py", line 200, in play
    raise e
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\game.py", line 196, in play
    game_agent.on_pause(frame_handler=frame_handler, **kwargs)
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\game_agent.py", line 120, in on_pause
    on_frame_handler_pause(**kwargs)
  File "c:\users\puter\anaconda3\lib\site-packages\serpent\game_agent.py", line 332, in on_record_pause
    data=[game_frame.frame_bytes for game_frame in game_frame_buffer.frames]
  File "c:\users\puter\anaconda3\lib\site-packages\h5py\_hl\group.py", line 106, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "c:\users\puter\anaconda3\lib\site-packages\h5py\_hl\dataset.py", line 100, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1530, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1552, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1607, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

**Comment by shisatum** [comment]
Closing: this was a PEBCAK. I needed to select the game window after both of these commands, for about 5 seconds:
```
serpent launch SuperFlight
serpent record SuperFlight SerpentSuperFlightGameAgent
```

**Comment by odwdinc** [comment]
how did you get past the TypeError: Object dtype dtype('O') has no native HDF5 equivalent
i'm seeing the same thing and selecting the game window after both of though commands is getting past

**Comment by mt-** [comment]
This issue should be re-opened.  I tested and get the following error on both Windows 10 and Linux when attempting to record.

  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 197, in play
    game_agent.on_pause(frame_handler=frame_handler, **kwargs)
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\serpent\game_agent.py", line 124, in on_pause
    on_frame_handler_pause(**kwargs)
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\serpent\game_agent.py", line 336, in on_record_pause
    data=[game_frame.frame_bytes for game_frame in game_frame_buffer.frames]
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\h5py\_hl\group.py", line 106, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\h5py\_hl\dataset.py", line 100, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1530, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1552, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1607, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent

**Comment by mt-** [comment]
Alright, the cause here appears to be that game_frame.frame_bytes is None.  Looking at the GameFrame class, either frame_bytes or frame_array is None, while the other has data.  In my case switching line 336 in game_agent.py to the following solves my issue:

                f.create_dataset(
                    f"{timestamp}-frames",
                    data=[game_frame.frame_array for game_frame in game_frame_buffer.frames]
                )

Still thinking about the best way to fix this so that it uses the correct instance variable.  I guess you can just put an if statement inside the list comprehension ala:

data=[game_frame.frame_array if game_frame.frame_array is not None else game_frame.frame_bytes for game_frame in game_frame_buffer.frames]

But readability isn't great here.

**Comment by mt-** [comment]
I did a bunch more digging, and I now understand that by choosing to apply frame transformations you're implicitly deciding on receiving bytes or an nd_array inside of GameFrame.  As I'm assuming all the published examples use some type of frame transformation (BindingOfIsaac is the one I've looked at), and thus this issue doesn't affect them.  

IMHO this a rather non-obvious side effect of choosing to apply a frame transformation.  Personally, I would convert everything to back to a nd_array after applying skimage, since nd_arrays are what I expect from a neural network standpoint.  That said, since GameFrame already has a getter that deals with this, then the proper fix seems to be to change the above code to:

                    data=[game_frame.frame for game_frame in game_frame_buffer.frames]

Note sure how I missed the existence of this getter yesterday.

**Comment by mt-** [comment]
A bit more digging, the reason you receive bytes is that |PNG is appended onto the end of the frame_transformation_pipeline_string inside of game.py, which means that by using a transformation you're implicitly saying to serpent you want a PNG as the dtype of the image.  This very non-obvious and surprising behavior.
