### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'win32gui'

### ISSUE THREAD

**Issue by woctezuma** [SerpentAI/SerpentAI#151]
* **Operating System:** Windows 10
* **Serpent.AI Version:** 2018.1.0
* **Game:** http://store.steampowered.com/app/573170/Fidel_Dungeon_Rescue/
* **Backend:** AMD Radeon HD 7770 1GB VRAM/Intel Pentium G2020 2.90Ghz

### Expected result

`serpent launch Fidel` terminates successfully.

### Encountered result

```
(serpent) C:\Users\Wok\SerpentAI>serpent launch Fidel
Traceback (most recent call last):
  File "c:\users\Wok\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\Wok\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Wok\Anaconda3\envs\serpent\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 349, in launch
    game = initialize_game(game_name)
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 580, in initialize_game
    game = game_class()
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\utilities.py", line 97, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\Wok\SerpentAI\plugins\SerpentFidelGamePlugin\files\serpent_Fidel_game.py", line 23, in __init__
    super().__init__(**kwargs)
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 57, in __init__
    self.window_controller = WindowController()
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\window_controller.py", line 11, in __init__
    self.adapter = self._load_adapter()()
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\window_controller.py", line 42, in _load_adapter
    from serpent.window_controllers.win32_window_controller import Win32WindowController
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\window_controllers\win32_window_controller.py", line 3, in <module>
    import win32gui
ModuleNotFoundError: No module named 'win32gui'
```

### Steps to reproduce

Have an installation of SerpentAI ready. Mine includes:

- Anaconda 5.0.1 (64-Bit edition) with Python 3.6
- Redis 3.0.504 (64-Bit edition, no choice)
- Tesseract 3.05.01

Then:

1. Create a plugin on Windows via `serpent generate game` 
2. In the dialog, answer with: `Fidel` and `steam`
3. Fill the values in `SerpentAI\plugins\SerpentFidelGamePlugin\filesserpent_Fidel_game.py` as follows:

```
        kwargs["window_name"] = "Fidel Dungeon Rescue"

        kwargs["app_id"] = "573170"
```  

4. Try to launch the game with `serpent launch Fidel`.

### Additional information

The module appears installed in `serpent` environment, but the import fails.

```
(serpent) C:\Users\Wok\SerpentAI>pip install win32gui
Requirement already satisfied: win32gui in c:\users\Wok\anaconda3\envs\serpent\lib\site-packages
Requirement already satisfied: win32core in c:\users\Wok\anaconda3\envs\serpent\lib\site-packages (from win32gui)

(serpent) C:\Users\Wok\SerpentAI>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32gui'
>>>
```

Uninstalling and then re-installing the module does not solve the problem:

```
(serpent) C:\Users\Wok\SerpentAI>pip uninstall win32gui
Uninstalling win32gui-221.6:
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\__init__.py
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\__pycache__\__init__.cpython-36.pyc
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\distutils\__init__.py
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\distutils\__pycache__\__init__.cpython-36.pyc
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\distutils\__pycache__\gui.cpython-36.pyc
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\distutils\gui.py
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\distutils\headers\win32gui.zip
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\gui.cp36-win_amd64.pyd
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\mfc140u.dll
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\mfcm140u.dll
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\ole.cp36-win_amd64.pyd
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32\ui.cp36-win_amd64.pyd
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32gui-221.6.dist-info\description.rst
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32gui-221.6.dist-info\installer
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32gui-221.6.dist-info\metadata
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32gui-221.6.dist-info\metadata.json
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32gui-221.6.dist-info\record
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32gui-221.6.dist-info\top_level.txt
  c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\win32gui-221.6.dist-info\wheel
Proceed (y/n)? y
  Successfully uninstalled win32gui-221.6

(serpent) C:\Users\Wok\SerpentAI>pip install win32gui
Collecting win32gui
  Using cached win32gui-221.6-cp36-cp36m-win_amd64.whl
Requirement already satisfied: win32core in c:\users\Wok\anaconda3\envs\serpent\lib\site-packages (from win32gui)
Installing collected packages: win32gui
Successfully installed win32gui-221.6

(serpent) C:\Users\Wok\SerpentAI>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32gui'
```

**Comment by woctezuma** [comment]
The issue is closed in #149, but I have the problem.

**Comment by shisatum** [comment]
My actual issue in #149 was not the need to reinstall explicitly, it was a conflicting Python3.6 installation from an earlier date. Removing the conflicting Python installation and reinstalling Anaconda and Serpent.AI resolved this error. You might not even need to reinstall anything, I just did it for my sake.

**Comment by woctezuma** [comment]
Thanks. Unfortunately, I have explored this direction, when I uninstalled everything (both Anaconda and my version of Python 3.6) and reinstalled Anaconda.

**Comment by Koura** [comment]
Does importing pywintypes (and or pythoncom) before importing win32gui inside the python interpreter solve the problem? If it does then try copying pythoncom36.dll and pywintypes36.dll from <your-path-to>/Anaconda3/envs/serpent/Lib/site-packages/pywin32_system32 to <your-path-to>/Anaconda3/envs/serpent/Lib/site-packages/win32 folder. That solved the problem in my case.

**Comment by nbrochu** [comment]
Acknowledged. Could it be an Anaconda 5.0.1 thing? I'm still running on 4 here and can't repro this.

**Comment by woctezuma** [comment]
Unfortunately, both `import pywintypes` and `import pythoncom` fail.

This is what I see in the `Lib\site-packages` where I would have expected to find `pywintypes` or `pythoncom`:

```
(serpent) C:\Users\Wok\Anaconda3\envs\serpent\Lib\site-packages>

[...]
PyScreeze-0.1.13.dist-info
pyscreeze
python_dateutil-2.6.1-py3.6.egg-info
pytweening
PyTweening-1.0.3.dist-info
pytz
pytz-2017.3-py3.6.egg-info
PyWavelets-0.5.2-py3.6.egg-info
pywt
pyximport
[...]
wheel
wheel-0.30.0-py3.6.egg-info
win32
win32core-221.36.dist-info
win32gui-221.6.dist-info
wincertstore-0.2-py3.6.egg-info
wincertstore.py
[...]
```

**Comment by woctezuma** [comment]
Alright, so `pip install pypiwin32` allowed me to move further:

- the game starts,
- but I get another message in the terminal.

It looks better.

```
(serpent) C:\Users\Wok\SerpentAI>serpent launch Fidel
Traceback (most recent call last):
  File "c:\users\Wok\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\Wok\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Wok\Anaconda3\envs\serpent\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 350, in launch
    game.launch()
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 119, in launch
    self.after_launch()
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 131, in after_launch
    self.window_controller.move_window(self.window_id, 0, 0)
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\window_controller.py", line 17, in move_window
    self.adapter.move_window(window_id, x, y)
  File "c:\users\Wok\anaconda3\envs\serpent\lib\site-packages\serpent\window_controllers\win32_window_controller.py", line 15, in move_window
    x0, y0, x1, y1 = win32gui.GetWindowRect(window_id)
pywintypes.error: (1400, 'GetWindowRect', 'Handle de fenêtre non valide.')
```

**Comment by woctezuma** [comment]
The issue is solved for `Super Hexagon`.

```
(serpent) C:\Users\Wok\SerpentAI>serpent launch SuperHexagon
{'width': 768, 'height': 480, 'x_offset': 8, 'y_offset': 31}

(serpent) C:\Users\Wok\SerpentAI>
```

**Comment by shillbear** [comment]
woctezuma u saved my life after 8 hours of trying
