### ISSUE TITLE
serpent generate new game  error

### ISSUE THREAD

**Issue by arixlin** [SerpentAI/SerpentAI#154]
* **Operating System:** Windows7 
* **Serpent.AI Version:** (2018.1.2)
* **Game:** (link to Steam page or Game)
* **Backend:** GPU/CPU

When I generate new game plugins :
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\github\SerpentAI\plugins\SerpenttestGamePlugin\plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpenttestGamePlugin)
  File "d:\anaconda3\lib\site-packages\offshoot\base.py", line 185, in executable_hook
    plugin_class.install()
  File "d:\anaconda3\lib\site-packages\offshoot\plugin.py", line 35, in install
    cls.install_files()
  File "d:\anaconda3\lib\site-packages\offshoot\plugin.py", line 118, in install_files
    raise e
  File "d:\anaconda3\lib\site-packages\offshoot\plugin.py", line 91, in install_files
    is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])
  File "d:\anaconda3\lib\site-packages\offshoot\plugin.py", line 235, in _validate_file_for_pluggable
    raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))
offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins\SerpenttestGamePlugin\files\serpent_test_game.py => Game

thx!

**Comment by mjaydenkim** [comment]
I got this too!
