### ISSUE TITLE
Error after the execution of the serpent generate game

### ISSUE THREAD

**Issue by pingqiang806796422** [SerpentAI/SerpentAI#166]
Please do not post installation issues here. An entire community is available to help over at [http://discuss.serpent.ai](http://discuss.serpent.ai).

* **Operating System:  Windows 
* **Serpent.AI Version: recen
* **Game: executable
* **Backend:** CPU

error:
     OFFSHOOT PLUGIN INSTALL: Installing files...

There was a problem during installation... Reverting!
Traceback (most recent call last):                                                                                        File "f:\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)                                                                                                 File "f:\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pingq\plugins\SerpentQSHGamePlugin\plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpentQSHGamePlugin)                                                                        File "f:\anaconda3\envs\serpent\lib\site-packages\offshoot\base.py", line 185, in executable_hook                         plugin_class.install()                                                                                                File "f:\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 35, in install
    cls.install_files()                                                                                                   File "f:\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 118, in install_files                         raise e                                                                                                               File "f:\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 91, in install_files                          is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])                       File "f:\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 235, in _validate_file_for_pluggable
    raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))        offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins\SerpentQSHGamePlugin\files\serpent_QSH_game.py => Game

**Comment by Ditchbuster** [comment]
i am also having this problem. on windows. i would go over to the discuss.serpent.ai but it doesn't seem to exist.
