### ISSUE TITLE
softmax not supported by tensorflow 1.4

### ISSUE THREAD

**Issue by LPiner** [SerpentAI/SerpentAI#171]
Fix seems to be to upgrade to tensorflow 1.5 with CUDA 9.

2018-05-26 19:10:46.345441: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1107] Ignoring gpu device (device: 1, name: GeForce GTX 1050, pci bus id: 0000:0b:00.0, compute capability: 6.1) with Cuda multiprocessor count: 5. The minimum required count is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROCESSOR_COUNT.
Traceback (most recent call last):
  File "/home/blitz/.local/share/virtualenvs/bit_blaster-lUOet_bL/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/home/blitz/.local/share/virtualenvs/bit_blaster-lUOet_bL/lib/python3.6/site-packages/serpent/serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/home/blitz/.local/share/virtualenvs/bit_blaster-lUOet_bL/lib/python3.6/site-packages/serpent/serpent.py", line 395, in train
    train_context(*args)
  File "/home/blitz/.local/share/virtualenvs/bit_blaster-lUOet_bL/lib/python3.6/site-packages/serpent/serpent.py", line 574, in train_context
    ContextClassifier.executable_train(epochs=int(epochs), validate=argv_is_true(validate), autosave=argv_is_true(autosave))
  File "/home/blitz/.local/share/virtualenvs/bit_blaster-lUOet_bL/lib/python3.6/site-packages/serpent/machine_learning/context_classification/context_classifier.py", line 106, in executable_train
    context_classifier.train(epochs=epochs, autosave=autosave, validate=validate)
  File "/home/blitz/.local/share/virtualenvs/bit_blaster-lUOet_bL/lib/python3.6/site-packages/serpent/machine_learning/context_classification/context_classifiers/cnn_inception_v3_context_classifier.py", line 44, in train
    predictions = Dense(len(self.training_generator.class_indices), activation='softmax')(output)
  File "/home/blitz/.local/share/virtualenvs/bit_blaster-lUOet_bL/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/blitz/.local/share/virtualenvs/bit_blaster-lUOet_bL/lib/python3.6/site-packages/keras/layers/core.py", line 881, in call
    output = self.activation(output)
  File "/home/blitz/.local/share/virtualenvs/bit_blaster-lUOet_bL/lib/python3.6/site-packages/keras/activations.py", line 29, in softmax
    return K.softmax(x)
  File "/home/blitz/.local/share/virtualenvs/bit_blaster-lUOet_bL/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2963, in softmax
    return tf.nn.softmax(x, axis=axis)
TypeError: softmax() got an unexpected keyword argument 'axis'

**Comment by supamonkey2000** [comment]
I am having this issue as well. This has been open for 15 days, could we get some assistance from more experienced users?

**Comment by supamonkey2000** [comment]
> Fix seems to be to upgrade to tensorflow 1.5 with CUDA 9.

Didn't see this part. I also found a fix by using Tensorflow 1.8. This could be closed now I think.
