### ISSUE TITLE
record - dtype('O') has no native HDF5 equivalent

### ISSUE THREAD

**Issue by thegarbadieer** [SerpentAI/SerpentAI#175]
* **Operating System:**Windows
* **Serpent.AI Version:** (e.g. 0.1.12b1)
* **Game:** Any
* **Backend:** CPU

### 
Writing Recorded Input Data to 'datasets/input_recording.h5'... (1/343)
Traceback (most recent call last):
  File "c:\users\ezra\anaconda3\envs\serpentai\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ezra\anaconda3\envs\serpentai\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ezra\Anaconda3\envs\serpentai\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\users\ezra\anaconda3\envs\serpentai\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\users\ezra\anaconda3\envs\serpentai\lib\site-packages\serpent\serpent.py", line 380, in record
    frame_spacing=int(frame_spacing)
  File "c:\users\ezra\anaconda3\envs\serpentai\lib\site-packages\serpent\game.py", line 201, in play
    raise e
  File "c:\users\ezra\anaconda3\envs\serpentai\lib\site-packages\serpent\game.py", line 197, in play
    game_agent.on_pause(frame_handler=frame_handler, **kwargs)
  File "c:\users\ezra\anaconda3\envs\serpentai\lib\site-packages\serpent\game_agent.py", line 124, in on_pause
    on_frame_handler_pause(**kwargs)
  File "c:\users\ezra\anaconda3\envs\serpentai\lib\site-packages\serpent\game_agent.py", line 336, in on_record_pause
    data=[game_frame.frame_bytes for game_frame in game_frame_buffer.frames]
  File "c:\users\ezra\anaconda3\envs\serpentai\lib\site-packages\h5py\_hl\group.py", line 106, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "c:\users\ezra\anaconda3\envs\serpentai\lib\site-packages\h5py\_hl\dataset.py", line 100, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1519, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1541, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1596, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent

### Steps to reproduce

1. Launch desired steam game
2. Run serpent record <game> <game_agent>
3. Pause game to save record.

**Comment by KobeAmerijckx** [comment]
I'm having this same issue. Did you solve this?
