### ISSUE TITLE
ConnectionError when using Hello World tutorial

### ISSUE THREAD

**Issue by supamonkey2000** [SerpentAI/SerpentAI#176]
Please do not post installation issues here. An entire community is available to help over at [http://discuss.serpent.ai](http://discuss.serpent.ai).

* **Operating System:** Windows
* **Serpent.AI Version:** latest from Pip, not sure how to view version number
* **Game:** N++ (https://store.steampowered.com/app/230270/N_NPLUSPLUS/)
* **Backend:** CPU (I think)

### Expected result

Terminal supposed to display "Hello world" as per the tutorial in the Wiki.

### Encountered result

A Python ConnectionError, with a lengthy stacktrace:

```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 484, in connect
    sock = self._connect()
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 541, in _connect
    raise err
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\client.py", line 667, in execute_command
    connection.send_command(*args)
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 585, in send_packed_command
    self.connect()
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 484, in connect
    sock = self._connect()
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 541, in _connect
    raise err
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\nplusplus\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\nplusplus\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\nplusplus\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\serpent\serpent.py", line 369, in play
    game.play(game_agent_class_name=game_agent_name, frame_handler=frame_handler)
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\serpent\game.py", line 150, in play
    **kwargs
  File "B:\Josh\Programming\Anaconda\nplusplus\plugins\SerpentNPPGameAgentPlugin\files\serpent_NPP_game_agent.py", line 7, in __init__
    super().__init__(**kwargs)
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\serpent\game_agent.py", line 91, in __init__
    self.visual_debugger = VisualDebugger()
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\serpent\visual_debugger\visual_debugger.py", line 19, in __init__
    self.clear_image_data()
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\serpent\visual_debugger\visual_debugger.py", line 51, in clear_image_data
    visual_debugger_keys = self.redis_client.keys(f"{config['visual_debugger']['redis_key_prefix']}*")
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\client.py", line 1032, in keys
    return self.execute_command('KEYS', pattern)
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\client.py", line 673, in execute_command
    connection.send_command(*args)
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 585, in send_packed_command
    self.connect()
  File "c:\programdata\anaconda3\envs\nplusplus\lib\site-packages\redis\connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
```

### Steps to reproduce

1. I followed the Hello World tutorial exactly, other than using a different game. The game successfully launches and is moved to the top left.
2. At one point I had to install `pypiwin32` to get rid of another error (this fix was recommended in another closed issue).
3. I ran `serpent play SuperHexagon SerpentSuperHexagonGameAgent` after modifying the GameAgent file as per the tutorial.

**Comment by nbrochu** [comment]
Redis is not running. Make sure you installed it as per wiki and that the service is running.

**Comment by supamonkey2000** [comment]
@nbrochu Thanks, that fixed it!
