### ISSUE TITLE
[Bug]Failed to capture region

### ISSUE THREAD

**Issue by FingerLiu** [SerpentAI/SerpentAI#185]
Please do not post installation issues here. An entire community is available to help over at [http://discuss.serpent.ai](http://discuss.serpent.ai).

* **Operating System:** macOS
* **Serpent.AI Version:** latest
* **Game:** SpeedRunner
* **Backend:** CPU

### Expected result
region img save to path.
### Encountered result
It raised error
### Steps to reproduce

1. launch SpeedRunners
2. capture frame
3. define regin `"EXIT": (25, 808, 70, 725),`
4. serpent capture region SpeedRunners 2 EXIT
```
Saving image 1/2 to disk...
Traceback (most recent call last):
  File "/Users/liupeng/Project/SerpentAI/venv/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/serpent/serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/serpent/serpent.py", line 410, in capture
    game.play(frame_handler="COLLECT_FRAME_REGIONS", interval=float(interval), region=extra)
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/serpent/game.py", line 201, in play
    raise e
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/serpent/game.py", line 197, in play
    game_agent.on_pause(frame_handler=frame_handler, **kwargs)
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/serpent/game_agent.py", line 124, in on_pause
    on_frame_handler_pause(**kwargs)
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/serpent/game_agent.py", line 243, in on_collect_frame_regions_pause
    skimage.io.imsave(f"{region_path}/region_{game_frame.timestamp}.png", frame_region)
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/skimage/io/_io.py", line 139, in imsave
    if is_low_contrast(arr):
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/skimage/exposure/exposure.py", line 504, in is_low_contrast
    limits = np.percentile(image, [lower_percentile, upper_percentile])
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4291, in percentile
    interpolation=interpolation)
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4033, in _ureduce
    r = func(a, **kwargs)
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4405, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 159, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/Users/liupeng/Project/SerpentAI/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```
Is it a bug?

**Comment by wallat** [comment]
I just solved the same problem with my code. Please define your region as `"EXIT": (25, 725, 70, 808)`.

---

This is because the script tries to extarct image by following code
```
return image[region_bounding_box[0]:region_bounding_box[2], region_bounding_box[1]:region_bounding_box[3]]
```

Thus we need to make sure: 
* `region_bounding_box[0]` is smaller than `region_bounding_box[2]`
* `region_bounding_box[1]` is smaller than `region_bounding_box[3]`

Or it will become a empty axes.
