### ISSUE TITLE
windows title cannot support chinese

### ISSUE THREAD

**Issue by luoy2** [SerpentAI/SerpentAI#186]
Please do not post installation issues here. An entire community is available to help over at [http://discuss.serpent.ai](http://discuss.serpent.ai).

* **Operating System:**  Windows 10
* **Serpent.AI Version:** (e.g. 0.1.12b1)
* **Game:** [Onmyoji](https://g37.gdl.netease.com/onmyoji_setup_6.3.0.exe) 
* **Backend:** GPU/CPU

### Steps to reproduce

1. download any chinese name, and put windows title in plugin file
2. serpent launch game
3. 
```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\serpent\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 355, in launch
    game = initialize_game(game_name)
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 580, in initialize_game
    game_class_mapping = offshoot.discover("Game")
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\offshoot\base.py", line 132, in discover
    valid, plugin_class = file_contains_pluggable(plugin_file_path, pluggable)
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\offshoot\base.py", line 167, in file_contains_pluggable
    syntax_tree = ast.parse(f.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x88 in position 316: illegal multibyte sequence
```

Solve:
inside `site-packages\offshoot\base.py`
change 2 places of
```
with open(file_path, "r") as f:
            syntax_tree = ast.parse(f.read())
```

to

```
with open(file_path, "r", encoding = 'utf-8') as f:
            syntax_tree = ast.parse(f.read())
```

**Comment by nbrochu** [comment]
Did you add `# -*- coding: utf-8 -*-` in your game plugin?

A Python file doesn't support unicode characters in the code without this, it has nothing to do with the framework

**Comment by luoy2** [comment]
yes i did. I added # -*- coding: utf-8 -*- to 4 files: 
1. `plugin.py` under `SerpentOnmyojiGameAgentPlugin`
2. `serpent_Onmyoji_game_agent.py` under `SerpentOnmyojiGameAgentPlugin\files`
3.`plugin.py` under `SerpentOnmyojiGamePlugin`
4. `serpent_Onmyoji_game.py` under `SerpentOnmyojiGamePlugin\files`

```
D:.
├─.idea
│  └─inspectionProfiles
├─config
├─datasets
│  ├─collect_frames
│  ├─collect_frames_for_context
│  └─current
└─plugins
    ├─SerpentOnmyojiGameAgentPlugin
    │  ├─files
    │  │  ├─helpers
    │  │  ├─ml_models
    │  │  └─__pycache__
    │  └─__pycache__
    └─SerpentOnmyojiGamePlugin
        ├─files
        │  ├─api
        │  │  └─__pycache__
        │  ├─data
        │  │  └─sprites
        │  └─__pycache__
        └─__pycache__
```

Unfortunately this didn't work.. I have to go to `offshoot\base.py` to edit the `with open`

**Comment by dbsxdbsx** [comment]
I got the same problem too.

**Comment by AlexanderLuo** [comment]
就是xdotool 获取窗口Id  可以自己改一下定位窗口的方法

**Comment by xiaoyuvax** [comment]
I found the same problem here as well,
add # -*- coding: utf-8 -*- doesn't help at all.

`with open(file_path, "r", encoding = 'utf-8') as f:
            syntax_tree = ast.parse(f.read())
`
is a reasonable solution.

**Comment by RMKD** [comment]
I'm having similar issues with `Don't Starve` - I'm guessing because of the apostrophe
