### ISSUE TITLE
Error running "serpent launch SuperHexagon" 

### ISSUE THREAD

**Issue by isqiwen** [SerpentAI/SerpentAI#190]
* **Operating System:** Linux /

### Encountered result
main.go:99: openScheme: "steam", "steam://run/221640"
main.go:108: desktop file: /usr/share/applications/steam.desktop
Traceback (most recent call last):
  File "/home/qiwen/anaconda3/envs/serpent/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/home/qiwen/anaconda3/envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/home/qiwen/anaconda3/envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 356, in launch
    game.launch()
  File "/home/qiwen/anaconda3/envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 119, in launch
    self.after_launch()
  File "/home/qiwen/anaconda3/envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 129, in after_launch
    self.window_id = self.window_controller.locate_window(self.window_name)
  File "/home/qiwen/anaconda3/envs/serpent/lib/python3.6/site-packages/serpent/window_controller.py", line 14, in locate_window
    return self.adapter.locate_window(name)
  File "/home/qiwen/anaconda3/envs/serpent/lib/python3.6/site-packages/serpent/window_controllers/linux_window_controller.py", line 15, in locate_window
    return subprocess.check_output(shlex.split(f"xdotool search --onlyvisible --name \"^{name}$\"")).decode("utf-8").strip()
  File "/home/qiwen/anaconda3/envs/serpent/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/qiwen/anaconda3/envs/serpent/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['xdotool', 'search', '--onlyvisible', '--name', '^SuperHexagon$']' returned non-zero exit status 1.

### 
```python
class SerpentSuperHexagonGame(Game, metaclass=Singleton):

    def __init__(self, **kwargs):
        kwargs["platform"] = "steam"

        kwargs["window_name"] = "SuperHexagon"

        kwargs["app_id"] = "221640"
        kwargs["app_args"] = None

**Comment by isqiwen** [comment]
no
