### ISSUE TITLE
xdotool: Search for ^Serpent.AI Dashboard$ returned non-zero exit status 1

### ISSUE THREAD

**Issue by ritiek** [SerpentAI/SerpentAI#191]
* **Operating System:** Linux
* **Serpent.AI Version:** As on dev branch (a1fd52ecdfc29a41eaac867aa623b8e72f097915)
* **Game:** [BombSquad](https://www.froemling.net/apps/bombsquad) ([download links](http://www.files.froemling.net/bombsquad/builds/))
* **Backend:** CPU

### Expected result

Bunch of "Hello World!" start streaming in the terminal ([as in wiki](https://github.com/SerpentAI/SerpentAI/wiki/The-Serpent.AI-Hello-World#hello-world)).

### Encountered result

```bash
$ serpent play BombSquad BombSquadGameAgent                                                                                   
Traceback (most recent call last):                                                                                                                                        
  File "/home/ritiek/.local/bin/serpent", line 11, in <module>                                                                                                            
    load_entry_point('SerpentAI', 'console_scripts', 'serpent')()                                                                                                         
  File "/home/ritiek/Downloads/SerpentAI/serpent/serpent.py", line 58, in execute                                                                                         
    command_function_mapping[command](*sys.argv[2:])                                                                                                                      
  File "/home/ritiek/Downloads/SerpentAI/serpent/serpent.py", line 419, in play
    game.launch(dry_run=True)
  File "/home/ritiek/Downloads/SerpentAI/serpent/game.py", line 129, in launch
    self.after_launch()
  File "/home/ritiek/Downloads/SerpentAI/serpent/game.py", line 183, in after_launch
    self.dashboard_window_id = self.window_controller.locate_window("Serpent.AI Dashboard")
  File "/home/ritiek/Downloads/SerpentAI/serpent/window_controller.py", line 14, in locate_window
    return self.adapter.locate_window(name)
  File "/home/ritiek/Downloads/SerpentAI/serpent/window_controllers/linux_window_controller.py", line 15, in locate_window
    return subprocess.check_output(shlex.split(f"xdotool search --onlyvisible --name \"^{name}$\"")).decode("utf-8").strip()
  File "/usr/local/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['xdotool', 'search', '--onlyvisible', '--name', '^Serpent.AI Dashboard$']' returned non-zero exit status 1.
```

### Steps to reproduce

1. Created game plugin
2. `$ serpent launch BombSquad` (launches the game in top left corner)
3. Created game agent plugin
3. `$ serpent play BombSquad BombSquadGameAgent` (causes the traceback)

My `serpent_BombSquad_game.py`:
```python
class SerpentBombSquadGame(Game, metaclass=Singleton):

    def __init__(self, **kwargs):
        kwargs["platform"] = "executable"
        kwargs["window_name"] = "BombSquad"
        kwargs["executable_path"] = "/home/ritiek/Downloads/bombsquad/bombsquad"

        super().__init__(**kwargs)

        self.api_class = BombSquadAPI
        self.api_instance = None
```

My `serpent_BombSquad_game_agent.py`:
```python
def handle_play(self, game_frame):
    print("Hello World!")
```

I confirmed that my window name is `BombSquad` with `$ serpent window_name` so I think the problem is somewhere else.

**Comment by Gotyk6** [comment]
If you have anything related to Dashboard in after_launch try to comment that part. I may be wrong, but this was way to deal with similar error when I got it.

**Comment by greyltc** [comment]
I see this too. Only on one of my two systems though (both Arch) so it's very strange. I assume it's because the `xdotool search` command is being run too fast (ie. before the window is available) so it returns 1 because it can't find the window. I think the right fix would be to handle the non-zero return code and re-do the search.

**Comment by greyltc** [comment]
But in your case here, the window is probably not named properly, I doubt you're searching for a window called "Serpent.AI Dashboard"

**Comment by greyltc** [comment]
FYI-- this PR fixes it for me https://github.com/SerpentAI/SerpentAI/pull/202
