### ISSUE TITLE
serpent generate game -> 'after_launch' method should not appear in the class

### ISSUE THREAD

**Issue by m1ndgames** [SerpentAI/SerpentAI#194]
Please do not post installation issues here. An entire community is available to help over at [http://discuss.serpent.ai](http://discuss.serpent.ai). <- Its dead

* **Operating System:** Windows
* **Serpent.AI Version:** latest release
* **Game:** Bubblo Bobble - c64 emulated
* **Backend:** GPU

### Expected result
Game plugin is created

### Encountered result
```
What is the name of the game? (Titleized, No Spaces i.e. AwesomeGame):
BuBo
How is the game launched? (One of: 'steam', 'executable', 'web_browser'):
executable
OFFSHOOT: Attempting to install SerpentBuBoGamePlugin...

OFFSHOOT PLUGIN INSTALL: Verifying that plugin dependencies are installed...


OFFSHOOT PLUGIN INSTALL: Installing files...


There was a problem during installation... Reverting!
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\SerpentAI\plugins\SerpentBuBoGamePlugin\plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpentBuBoGamePlugin)
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\offshoot\base.py", line 185, in executable_hook
    plugin_class.install()
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 35, in install
    cls.install_files()
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 118, in install_files
    raise e
  File "c:\programdata\anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 106, in install_files
    raise PluginError("Offshoot Plugin File Install Errors: %s" % "".join(install_messages))
offshoot.plugin.PluginError: Offshoot Plugin File Install Errors:
serpent_BuBo_game.py: SerpentBuBoGame: 'after_launch' method should not appear in the class.

(serpent) C:\SerpentAI>
```

### Steps to reproduce

1. No idea, its been a while since i used serpentai and in the older version i didnt have this issue

**Comment by Gotyk6** [comment]
Hi,
I probably had similar issue. If I remember correctly this are steps to deal with that:
1. Comment after_launch method in game plugin
2. Serpent activate
3.  Uncomment 
I do not remember syntax of serpent activate, but probably serpent activate GAME_PLUGIN_NAME
