### ISSUE TITLE
Hello world Tutorial Error 

### ISSUE THREAD

**Issue by LeonardoDavid** [SerpentAI/SerpentAI#198]
* **Operating System:**  Windows
* **Serpent.AI Version:** not sure 
* **Game:** (Cuphead) Executable 
* **Backend:** GPU

i followed the hello world tutorial, created plug in for cuphead executable game when i launch the game  i get this error 

```
(AI) C:\Users\ANTONY\SerpentAI>serpent launch cuphead
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\ai\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\ai\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\AI\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\envs\ai\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\programdata\anaconda3\envs\ai\lib\site-packages\serpent\serpent.py", line 355, in launch
    game = initialize_game(game_name)
  File "c:\programdata\anaconda3\envs\ai\lib\site-packages\serpent\serpent.py", line 580, in initialize_game
    game_class_mapping = offshoot.discover("Game")
  File "c:\programdata\anaconda3\envs\ai\lib\site-packages\offshoot\base.py", line 147, in discover
    exec(import_statement)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'plugins.SerpentCupheadGamePlugin'
```

**Comment by Sytul** [comment]
Leonardo, sorry this answer won't be too much help but I have the exact same problem and I've been meaning to add my details to this problem.  Details are as follows:

Operating System: Windows 10
Serpent.AI Version: 3.13
Game: TiamatX 
Backend: GPU

Error messages is as follows:
(GamingAI) C:\Users\Simon>serpent launch TiamatX
Traceback (most recent call last):
  File "e:\anaconda3\envs\gamingai\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda3\envs\gamingai\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\envs\GamingAI\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "e:\anaconda3\envs\gamingai\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "e:\anaconda3\envs\gamingai\lib\site-packages\serpent\serpent.py", line 355, in launch
    game = initialize_game(game_name)
  File "e:\anaconda3\envs\gamingai\lib\site-packages\serpent\serpent.py", line 580, in initialize_game
    game_class_mapping = offshoot.discover("Game")
  File "e:\anaconda3\envs\gamingai\lib\site-packages\offshoot\base.py", line 147, in discover
    exec(import_statement)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'plugins.SerpenttiamatXGamePlugin'

I think the issue is around the capitalisation and lowercasing of the game plugin name.  If I run serpent plugins I get the following:

ACTIVE Plugins:
SerpentTiamatXGamePlugin

However, note that in the error message, TiamatX is in lowercase, so it's looking for tiamatX, which isn't the name of my plugin, and there is no plugin anywhere in my plugins director called SerpenttiamatXGamePlugin.  It's called SerpentTiamatXGamePlugin.  I haven't yet worked out why SerpentAI is lowercasing that 'T' in Tiamat and was hoping someone could shed light on this.

Happy to provide more information if needs be.

Thanks

**Comment by LeonardoDavid** [comment]
@Sytul Hey i fixed that error by installing windows 10 SDK
