### ISSUE TITLE
Problem during installation, invalid pluggable

### ISSUE THREAD

**Issue by JulianNorton** [SerpentAI/SerpentAI#27]
Windows 10, followed the installation wiki.

```
What is the name of the game? (Titleized, No Spaces i.e. AwesomeGame):
Squarebrawl
How is the game launched? (One of: 'steam', 'executable'):
steam
OFFSHOOT: Attempting to install SerpentSquarebrawlGamePlugin...

OFFSHOOT PLUGIN INSTALL: Verifying that plugin dependencies are installed...


OFFSHOOT PLUGIN INSTALL: Installing files...


There was a problem during installation... Reverting!
Traceback (most recent call last):
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\j\SerpentAI\plugins\SerpentSquarebrawlGamePlugin\plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpentSquarebrawlGamePlugin)
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\site-packages\offshoot\base.py", line 178, in executable_hook
    plugin_class.install()
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\site-packages\offshoot\plugin.py", line 35, in install
    cls.install_files()
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\site-packages\offshoot\plugin.py", line 118, in install_files
    raise e
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\site-packages\offshoot\plugin.py", line 91, in install_files
    is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\site-packages\offshoot\plugin.py", line 235, in _validate_file_for_pluggable
    raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))
offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins\SerpentSquarebrawlGamePlugin\files\serpent_Squarebrawl_game.py => Game

(serpent) C:\Users\j\SerpentAI>
```

It does create files, but modifying it based on the readme doesn't work.

https://gist.github.com/JulianNorton/0b070bcb208e013bd648bc4461a0cfbf

```
(serpent) C:\Users\j\SerpentAI>serpent launch Squarebrawl
Traceback (most recent call last):
  File "C:\Users\j\AppData\Local\Programs\Python\Python36-32\Scripts\serpent-script.py", line 11, in <module>
    load_entry_point('SerpentAI==0.1.0b1', 'console_scripts', 'serpent')()
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\site-packages\serpent\serpent.py", line 47, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\site-packages\serpent\serpent.py", line 212, in launch
    raise Exception(f"Game '{game_name}' wasn't found. Make sure the plugin is installed.")
Exception: Game 'Squarebrawl' wasn't found. Make sure the plugin is installed.

(serpent) C:\Users\j\SerpentAI>serpent launch Squarebrawl
Traceback (most recent call last):
  File "C:\Users\j\AppData\Local\Programs\Python\Python36-32\Scripts\serpent-script.py", line 11, in <module>
    load_entry_point('SerpentAI==0.1.0b1', 'console_scripts', 'serpent')()
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\site-packages\serpent\serpent.py", line 47, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\users\j\appdata\local\programs\python\python36-32\lib\site-packages\serpent\serpent.py", line 212, in launch
    raise Exception(f"Game '{game_name}' wasn't found. Make sure the plugin is installed.")
Exception: Game 'Squarebrawl' wasn't found. Make sure the plugin is installed.

```

**Comment by pyloque** [comment]
me the same

**Comment by nbrochu** [comment]
I need to update offshoot to not gobble up exceptions. Can you go in IPython and run `from serpent.game import Game` and paste the traceback, if any?

**Comment by JulianNorton** [comment]
Not sure I understand, is this what you mean?
![capture](https://user-images.githubusercontent.com/2412992/30775215-8da4e5e2-a05d-11e7-9a7e-80d95214c6e6.JPG)

**Comment by nbrochu** [comment]
Yes, but do it from the Anaconda Prompt on Windows

**Comment by JulianNorton** [comment]
```
(serpent) C:\Users\j\SerpentAI> from serpent.game import Game
'from' is not recognized as an internal or external command,
operable program or batch file.

(serpent) C:\Users\j\SerpentAI>
```

Happy to chat over a DM if it's easier to help debug.

**Comment by nbrochu** [comment]
Don't know if you have discord, but you can join https://discord.gg/9D5SuxH and IM me (Serpent.AI) directly with issues or post in #project-serpent-help. I'll update the issue here if it seems to be a widespread problem.

**Comment by pyloque** [comment]
well, solved! you must cd SerpentAI directory!

**Comment by joshuamsmith** [comment]
Am in the Anaconda console with cwd of SerpentAI and getting same issues mentioned.
**Windows 10, fresh Anaconda install**

In Anaconda prompt _(serpent) C:\Users\me\OneDrive\Projects\Python\SerpentAI>_

If I try *serpent generate game* again, I get 

> Cannot create a file when that file already exists: 'plugins\\SerpentFactorioGamePlugin'

So I then try to *serpent start Factorio* and I get 

> File "c:\users\me\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 212, in launch
    raise Exception(f"Game '{game_name}' wasn't found. Make sure the plugin is installed.")
Exception: Game 'Factorio' wasn't found. Make sure the plugin is installed.

**Comment by CorentinJ** [comment]
Same issue but on Ubuntu. Tried with SuperHexagon and SuperCrateBox, same output:

`What is the name of the game? (Titleized, No Spaces i.e. AwesomeGame): 
SuperCrateBox            
How is the game launched? (One of: 'steam', 'executable'): 
steam
OFFSHOOT: Attempting to install SerpentSuperCrateBoxGamePlugin...

OFFSHOOT PLUGIN INSTALL: Verifying that plugin dependencies are installed...


OFFSHOOT PLUGIN INSTALL: Installing files...


There was a problem during installation... Reverting!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/valiox/Workspace/serpent/plugins/SerpentSuperCrateBoxGamePlugin/plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpentSuperCrateBoxGamePlugin)
  File "/usr/local/lib/python3.6/dist-packages/offshoot/base.py", line 178, in executable_hook
    plugin_class.install()
  File "/usr/local/lib/python3.6/dist-packages/offshoot/plugin.py", line 35, in install
    cls.install_files()
  File "/usr/local/lib/python3.6/dist-packages/offshoot/plugin.py", line 118, in install_files
    raise e
  File "/usr/local/lib/python3.6/dist-packages/offshoot/plugin.py", line 91, in install_files
    is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])
  File "/usr/local/lib/python3.6/dist-packages/offshoot/plugin.py", line 235, in _validate_file_for_pluggable
    raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))
offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins/SerpentSuperCrateBoxGamePlugin/files/serpent_SuperCrateBox_game.py => Game
`

**Comment by JulianNorton** [comment]
I've confirmed this error is happening on MacOS too @CorentinJ 


```
What is the name of the game? (Titleized, No Spaces i.e. AwesomeGame):
Squarebrawl
How is the game launched? (One of: 'steam', 'executable'):
steam
OFFSHOOT: Attempting to install SerpentSquarebrawlGamePlugin...

OFFSHOOT PLUGIN INSTALL: Verifying that plugin dependencies are installed...


OFFSHOOT PLUGIN INSTALL: Installing files...


There was a problem during installation... Reverting!
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/j/SerpentAI/plugins/SerpentSquarebrawlGamePlugin/plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpentSquarebrawlGamePlugin)
  File "/Users/j/.virtualenvs/serpent/lib/python3.6/site-packages/offshoot/base.py", line 178, in executable_hook
    plugin_class.install()
  File "/Users/j/.virtualenvs/serpent/lib/python3.6/site-packages/offshoot/plugin.py", line 35, in install
    cls.install_files()
  File "/Users/j/.virtualenvs/serpent/lib/python3.6/site-packages/offshoot/plugin.py", line 118, in install_files
    raise e
  File "/Users/j/.virtualenvs/serpent/lib/python3.6/site-packages/offshoot/plugin.py", line 91, in install_files
    is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])
  File "/Users/j/.virtualenvs/serpent/lib/python3.6/site-packages/offshoot/plugin.py", line 235, in _validate_file_for_pluggable
    raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))
offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins/SerpentSquarebrawlGamePlugin/files/serpent_Squarebrawl_game.py => Game
(serpent) js-iMac:SerpentAI j$ ls
config			offshoot.manifest.json	plugins
datasets		offshoot.yml		requirements.txt
(serpent) js-iMac:SerpentAI j$
```

**Comment by nbrochu** [comment]
The problem is Offshoot will return this error if *anything* goes wrong. I'm gonna have to update it to optionally let the exception through to help. If you want faster assistance. You can try the discord.

**Comment by nbrochu** [comment]
If you encounter *offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable*, something went wrong in your setup. It is unlikely to be an issue with the Serpent.AI codebase itself. Make sure you are in the proper virtualenv. Try going in `ipython` or  `python` and execute the following statements:

`import serpent.game`

`import serpent.game_agent`

You can try getting some help from the community by pasting any error that shows up in *#project-serpent-help* on [Discord](https://discord.gg/9D5SuxH).
