### ISSUE TITLE
window position range illegal when launch the game

### ISSUE THREAD

**Issue by pyloque** [SerpentAI/SerpentAI#28]
applescript.ScriptError: System Events got an error: Can’t set process "Doodle God" to {{0}, {0}}. (-10006) app='System Events' range=107-115

**Comment by pyloque** [comment]
Traceback (most recent call last):
  File "/Users/qianwp/Envs/serpent/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 47, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 214, in launch
    game().launch()
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 114, in launch
    self.after_launch()
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 126, in after_launch
    self.window_controller.move_window(self.window_id, 0, 0)
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/window_controller.py", line 17, in move_window
    self.adapter.move_window(window_id, x, y)
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/serpent/window_controllers/darwin_window_controller.py", line 19, in move_window
    ''').run()
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/applescript/__init__.py", line 90, in run
    return self._unpackresult(*self._script.executeAndReturnError_(None))
  File "/Users/qianwp/Envs/serpent/lib/python3.6/site-packages/applescript/__init__.py", line 65, in _unpackresult
    raise ScriptError(errorinfo)
applescript.ScriptError: System Events got an error: Can’t set process "Doodle God" to {{0}, {0}}. (-10006) app='System Events' range=107-115

**Comment by d0p3t** [comment]
Is your window is called "Doodle God"?

For debugging purposes, could you please run the following applescript in AppleScript Editor while running the game.

```
tell application "System Events" to tell window 1 of process "Doodle God"
    return get position
end tell
```

It should return the x,y position of the window.

**Comment by pyloque** [comment]
solved, I mistaked the window name

**Comment by pyloque** [comment]
close it
