### ISSUE TITLE
Windows 7 "serpent setup" error

### ISSUE THREAD

**Issue by hobbycoder7** [SerpentAI/SerpentAI#33]
Following the Windows Install guide and got to ```serpent setup``` which produced this error:
```
Which backend do you plan to use for Tensorflow (One of: 'CPU', 'GPU' - Note: GP
U backend can only be used on NVIDIA GTX 600 series and up):
CPU
Installing dependencies...
Traceback (most recent call last):
  File "e:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Python36\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "e:\python36\lib\site-packages\serpent\serpent.py", line 47, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "e:\python36\lib\site-packages\serpent\serpent.py", line 147, in setup
    subprocess.call(shlex.split("conda install numpy scipy scikit-image scikit-l
earn h5py -y"))
  File "e:\python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "e:\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "e:\python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
After some googling I was able to find this answer: https://stackoverflow.com/a/4616867 which worked.

Changing line 147 in serpent.py
```subprocess.call(shlex.split("conda install numpy scipy scikit-image scikit-learn h5py -y"))```
to
```subprocess.call(shlex.split("conda install numpy scipy scikit-image scikit-learn h5py -y"), shell=True)```
fixed the problem.

I haven't submitted a PR since I'm not sure if this is a Win 7 only problem or not. I don't have access to Windows 10 and I don't see any other reports of this.

**Comment by nbrochu** [comment]
People seem to be seeing on Win 10 too. You can PR. The other fix is to have 3 Anaconda entries in %PATH%

**Comment by hobbycoder7** [comment]
PR Submitted.
