### ISSUE TITLE
Ubuntu: Xlib.error.DisplayConnectionError

### ISSUE THREAD

**Issue by kkxue** [SerpentAI/SerpentAI#39]
Environment: Ubuntu 16.04 LTS
Hi,I am following Linux Installation Guide,everything goes fine but the last one:
serpent setup 
```
Collecting PyAutoGUI (from -r requirements.txt (line 12))
  Using cached PyAutoGUI-0.9.36.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rup9jygb/PyAutoGUI/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "/tmp/pip-build-rup9jygb/PyAutoGUI/pyautogui/__init__.py", line 115, in <module>
        from . import _pyautogui_x11 as platformModule
      File "/tmp/pip-build-rup9jygb/PyAutoGUI/pyautogui/_pyautogui_x11.py", line 160, in <module>
        _display = Display(os.environ['DISPLAY'])
      File "/root/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
        self.display = _BaseDisplay(display)
      File "/root/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
        protocol_display.Display.__init__(self, *args, **keys)
      File "/root/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/Xlib/protocol/display.py", line 167, in __init__
        raise error.DisplayConnectionError(self.display_name, r.reason)
    Xlib.error.DisplayConnectionError: Can't connect to display ":1": b'No protocol specified\n'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rup9jygb/PyAutoGUI/
```

**Comment by kkxue** [comment]
[https://stackoverflow.com/questions/31902846/how-to-fix-error-xlib-error-displayconnectionerror-cant-connect-to-display-0](url)
seems like a bug of python3-xlib.
Temporary workaround is: (tested)
$ xhost +

**Comment by Prasad8897** [comment]
xhost +
is giving me this error
'access control disabled, clients can connect from any host'

**Comment by dpacmen** [comment]
^That's not an error. Try running  sudo pip install pyautogui
after xhost+ , It'll work
