### ISSUE TITLE
External command "xdotool getwindowgeometry {window_id}" fails

### ISSUE THREAD

**Issue by CorentinJ** [SerpentAI/SerpentAI#53]
I managed to generate a plugin with serpent for [Super Crate Box](http://store.steampowered.com/app/212800/Super_Crate_Box/), but when I launch the game it crashes after the game has booted. I installed xdotool through apt-get, running on Ubuntu 64bits.

```
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
xdotool: Unknown command: 0
Run 'xdotool help' if you want a command list
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
xdotool: Unknown command: 67108867
Run 'xdotool help' if you want a command list
xdotool: Unknown command: 67108867
Run 'xdotool help' if you want a command list
Traceback (most recent call last):
  File "/home/valiox/.pyenv/versions/serpent/bin/serpent", line 11, in <module>
    load_entry_point('SerpentAI==0.1.4b1', 'console_scripts', 'serpent')()
  File "/home/valiox/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 47, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/home/valiox/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 214, in launch
    game().launch()
  File "/home/valiox/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 114, in launch
    self.after_launch()
  File "/home/valiox/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 129, in after_launch
    self.window_geometry = self.extract_window_geometry()
  File "/home/valiox/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 178, in extract_window_geometry
    return self.window_controller.get_window_geometry(self.window_id)
  File "/home/valiox/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/window_controller.py", line 29, in get_window_geometry
    return self.adapter.get_window_geometry(window_id)
  File "/home/valiox/.pyenv/versions/3.6.2/envs/serpent/lib/python3.6/site-packages/serpent/window_controllers/linux_window_controller.py", line 33, in get_window_geometry
    window_geometry = subprocess.check_output(shlex.split(f"xdotool getwindowgeometry {window_id}")).decode("utf-8").strip()
  File "/home/valiox/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/valiox/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['xdotool', 'getwindowgeometry', '67108868', '67108867']' returned non-zero exit status 1.
```

**Comment by nbrochu** [comment]
This means the game has multiple windows (either visible or not) and SerpentAI doesn't know which to pick. I'm still debating how to tackle this scenario in the framework but if you give me a little time I can get you something that will get it working for your game.

**Comment by kkxue** [comment]
Error happend +1 in Ubuntu 16.04 LTS

**Comment by kkxue** [comment]
But i found the reason is i haven't start the game.

**Comment by CorentinJ** [comment]
I just picked that game because it's free and I don't have the grand luxury of being able to afford superhexagon

**Comment by CorentinJ** [comment]
Are you sure it's not something to do with xdotool? I had only one window in that game and here I'm getting another error on SpeedRunners

```
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
{'width': 1920, 'height': 1080, 'x_offset': 0, 'y_offset': 0}
```

**Comment by d0p3t** [comment]
Are you running* SpeedRunners* and *Super Crate Box* in windowed mode? As far as I know, full screen isn't supported.

**Comment by CorentinJ** [comment]
> Are you running* SpeedRunners* and Super Crate Box in windowed mode? As far as I know, full screen isn't supported.

Yup

**Comment by nbrochu** [comment]
I could see 2 window ids in the xdotool stracktrace, that's why i suggested that.

**Comment by nbrochu** [comment]
I did this to handle Nuclear Throne (another Vlambeer game) because I had the same 2 window issue:

Override `after_launch` in your game plugin by adding:

```python
    def after_launch(self):
        self.is_launched = True

        time.sleep(5)

        self.window_id = self.window_controller.locate_window(self.window_name).split("\n")[1]

        self.window_controller.resize_window(self.window_id, 1024, 768)  #Optional - Can change or skip

        self.window_controller.move_window(self.window_id, 0, 0)
        self.window_controller.focus_window(self.window_id)

        self.window_geometry = self.extract_window_geometry()
        print(self.window_geometry)
```

Give it a try!

**Comment by outterback** [comment]
Hi @nbrochu 

I had the same issue running FCEUX under Arch, but your comment worked for me. However, the code goes into the Game class (SerpentGameNamePlugin/files/serpent_GameName_game.py) and not in the Game Plugin class. 

This is apparent from the stacktrace:
`  File "/home/oscar/.local/share/virtualenvs/dev-lab-S8LRmcaK/lib/python3.6/site-packages/serpent/game.py", line 134, in after_launch
    self.window_geometry = self.extract_window_geometry()
  File "/home/oscar/.local/share/virtualenvs/dev-lab-S8LRmcaK/lib/python3.6/site-packages/serpent/game.py", line 212, in extract_window_geometry
`

where after_launch resides in serpent/game.py.

Was the behavior different back when you wrote the comment?
