### ISSUE TITLE
Error running "serpent launch LegendOfNumbers"

### ISSUE THREAD

**Issue by shkarupa-alex** [SerpentAI/SerpentAI#55]
Game http://store.steampowered.com/app/485760/Legend_of_Numbers/

Traceback (most recent call last):
  File "/Users/alex/.virtualenvs/serpent/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/Users/alex/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 47, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/Users/alex/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 214, in launch
    game().launch()
  File "/Users/alex/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/game.py", line 114, in launch
    self.after_launch()
  File "/Users/alex/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/game.py", line 126, in after_launch
    self.window_controller.move_window(self.window_id, 0, 0)
  File "/Users/alex/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/window_controller.py", line 17, in move_window
    self.adapter.move_window(window_id, x, y)
  File "/Users/alex/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/window_controllers/darwin_window_controller.py", line 19, in move_window
    ''').run()
  File "/Users/alex/.virtualenvs/serpent/lib/python3.6/site-packages/applescript/__init__.py", line 90, in run
    return self._unpackresult(*self._script.executeAndReturnError_(None))
  File "/Users/alex/.virtualenvs/serpent/lib/python3.6/site-packages/applescript/__init__.py", line 65, in _unpackresult
    raise ScriptError(errorinfo)
applescript.ScriptError: System Events got an error: Can’t set process "Legend of Numbers" to {{0}, {0}}. (-10006) app='System Events' range=114-122

**Comment by d0p3t** [comment]
I am getting no issues with launching *Legend Of Numbers* on macOS via Steam.

Could you please post line 10-23 of `serpent_LegendOfNumbers_game.py` from the game plugin?

**Comment by nbrochu** [comment]
Usually this error on macOS is when you don't specify the right process name in `kwargs["window_name"]` in the game plugin

**Comment by inksong** [comment]
@shkarupa-alex Hi.
Use Activity Monitor to locate the game process
Just like Nuclear Throne 's process name is "nuclearthrone" under macos 10.12.6
I thought @nbrochu has made a func to locate the game process's name

**Comment by nbrochu** [comment]
Yes, starting in 0.1.6b1 you can run `serpent window_name`.

Start the game manually. It will ask you to press any key and focus the game window. Do it within 5 seconds and stay there for another 5 seconds. Then go back to the Terminal and you should see the exact value you should use for `kwargs["window_name"]`

I'm adding a wiki entry for this. Feel free to reopen the issue is you need more help or join the 
[Discord](https://discord.gg/9D5SuxH).
