### ISSUE TITLE
Error while attempting to train context on macOS High Sierra

### ISSUE THREAD

**Issue by kjullien** [SerpentAI/SerpentAI#56]
Hello I got an error :
```bash
(serpent) ❯ serpent train context 15
Using TensorFlow backend.
Found 184 images belonging to 1 classes.
Found 17 images belonging to 1 classes.
2017-09-26 22:00:11.280125: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-26 22:00:11.280151: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-26 22:00:11.280156: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-26 22:00:11.280160: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Epoch 1/15
Traceback (most recent call last):
  File "/Users/kevin/.virtualenvs/serpent/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/Users/kevin/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 47, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/Users/kevin/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 247, in train
    train_context(*args)
  File "/Users/kevin/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 390, in train_context
    ContextClassifier.executable_train(epochs=int(epochs))
  File "/Users/kevin/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/machine_learning/context_classification/context_classifier.py", line 106, in executable_train
    context_classifier.train(epochs=epochs)
  File "/Users/kevin/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/machine_learning/context_classification/context_classifiers/cnn_inception_v3_context_classifier.py", line 56, in train
    class_weight="auto"
  File "/Users/kevin/.virtualenvs/serpent/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/Users/kevin/.virtualenvs/serpent/lib/python3.6/site-packages/keras/engine/training.py", line 2042, in fit_generator
    class_weight=class_weight)
  File "/Users/kevin/.virtualenvs/serpent/lib/python3.6/site-packages/keras/engine/training.py", line 1756, in train_on_batch
    check_batch_axis=True)
  File "/Users/kevin/.virtualenvs/serpent/lib/python3.6/site-packages/keras/engine/training.py", line 1393, in _standardize_user_data
    self._feed_output_shapes)
  File "/Users/kevin/.virtualenvs/serpent/lib/python3.6/site-packages/keras/engine/training.py", line 277, in _check_loss_and_target_compatibility
    ' while using as loss `categorical_crossentropy`. '
ValueError: You are passing a target array of shape (32, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via:
``
from keras.utils.np_utils import to_categorical
y_binary = to_categorical(y_int)
``

Alternatively, you can use the loss function `sparse_categorical_crossentropy` instead, which does expect integer targets.
```

I have no idea why this is happening, tried googling the error message itself but the answers I found were way to low level for me to comprehend...
I am using the latest Macbook Pro 15" model if that helps and macOS High Sierra 10.13.

**Comment by kjullien** [comment]
You need at least 2 contexts to start training.

"Classify these images, you have 1 option, and are always right" -Scotch
