### ISSUE TITLE
Cannot reshape array (hello world example)

### ISSUE THREAD

**Issue by derdav3** [SerpentAI/SerpentAI#78]
* **Operating System:** Linux/Windows/macOS
macOS
* **Serpent Version:** (e.g. 0.1.6b1)
no idea - `--v` didnt work
* **Game:** (link to steam page or game)
http://store.steampowered.com/app/363970/Clicker_Heroes/
* **Backend:** GPU/CPU
CPU

### Expected result
followed the hello world and expected some printouts in the console, but only the window moved to the upper left and this output in the console: 
```
{'width': 1136, 'height': 642, 'x_offset': 0, 'y_offset': 42}
Traceback (most recent call last):
  File "/Users/dave/.virtualenvs/serpent/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/Users/dave/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 47, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/Users/dave/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 233, in play
    game.play(game_agent_class_name=game_agent_name, frame_handler=frame_handler)
  File "/Users/dave/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/game.py", line 157, in play
    game_frame = self.grab_latest_frame()
  File "/Users/dave/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/game.py", line 215, in grab_latest_frame
    3
  File "/Users/dave/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/frame_grabber.py", line 74, in get_frames
    frame_array = np.fromstring(frame_bytes, dtype="uint8").reshape(frame_shape)
ValueError: cannot reshape array of size 8751744 into shape (642,1136,3)
```
  
thx - slowly getting there...looking forward to test some ideas once this runs :)

**Comment by nbrochu** [comment]
You can check the version by running only `serpent`.

Upgrade to the latest with `pip install --upgrade SerpentAI`. There are updates almost everyday during beta!

This problem should be resolved on latest beta. Feel free to reopen the issue if you are still having issues, I'll give it a shot with Clickers Heroes (Incremental games are a perfect target for this BTW!)
