### ISSUE TITLE
[Errno 13] Permission denied - When trying to launch game executable on macOS

### ISSUE THREAD

**Issue by kjullien** [SerpentAI/SerpentAI#79]
* **Operating System:** macOS
* **Serpent Version:** v0.1.7b1
* **Game:** Chess.app on macOS
* **Backend:** CPU

I am trying to generate a game with serpent for a macOS executable, here Chess.app (a default mac app).

When I `serpent launch Chess` I get an error :
```
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/serpent/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/Users/user/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 48, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/Users/user/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 216, in launch
    game().launch()
  File "/Users/user/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/game.py", line 112, in launch
    self.game_launcher().launch(**self.kwargs)
  File "/Users/user/.virtualenvs/serpent/lib/python3.6/site-packages/serpent/game_launchers/executable_game_launcher.py", line 22, in launch
    subprocess.Popen(shlex.split(executable_path))
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

**Comment by kjullien** [comment]
The config is :
```
kwargs["platform"] = "executable"
kwargs["window_name"] = "Chess"
kwargs["executable_path"] = "/Applications/Chess.app"
```

Steam works fine,
Web_browser won't work with Chrome on macOS, will resize and place window if open already, but not navigate to, but that's another issue I might open next.

**Comment by nbrochu** [comment]
You open Apps on macOS through the command line with `open -a Chess`

**Comment by kjullien** [comment]
Yes `open -a Chess` worked my bad I thought you had to pass in the executable path and it would run it.

**Comment by nbrochu** [comment]
Depends on what you want to do. It basically executes a terminal command.
